"""empty message

Revision ID: 23c2fe119a01
Revises: d61d7a467220
Create Date: 2024-03-07 18:30:03.950432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c2fe119a01'
down_revision = 'd61d7a467220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
