"""empty message

Revision ID: 76d8071e142c
Revises: b17cbeb057e6
Create Date: 2024-07-17 14:32:54.641279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import text

Base = declarative_base()

# revision identifiers, used by Alembic.
revision = '76d8071e142c'
down_revision = 'b17cbeb057e6'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_context().connection
    table_columns = op.get_context().dialect.get_columns(conn, 'order_items')
    created_at_col = next((column for column in table_columns if column['name'] == "created_at"), None)

    if not created_at_col:
        with op.batch_alter_table('order_items', schema=None) as batch_op:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    statement = text("""UPDATE order_items SET created_at = (SELECT orders.created_at FROM orders WHERE orders.id = order_items.order_id) WHERE created_at IS NULL""")
    conn.execute(statement)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###

