"""empty message

Revision ID: 92feefdf609d
Revises: ecf72a574f2b
Create Date: 2025-06-20 18:31:53.968788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92feefdf609d'
down_revision = 'ecf72a574f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed_on',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed_on',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
