"""empty message

Revision ID: 993700eb81e4
Revises: 229379c75d88
Create Date: 2025-04-22 17:42:52.956467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993700eb81e4'
down_revision = '229379c75d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
