"""empty message

Revision ID: c5597fb2b0dc
Revises: e7f5905b5e15
Create Date: 2025-06-12 14:45:06.295884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5597fb2b0dc'
down_revision = 'e7f5905b5e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('registered_on',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('registered_on',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
